# Test the Docstrings Pressure atmospheric transparency Emulator

- author : Sylvie Dagoret-Campagne
- affiliation : IJCLab/IN2P3/CNRS
- creation date : 2023/11/01
- last update : 2023/11/02


In [1]:
from getObsAtmo.getObsAtmo import ObsAtmo,Dict_Of_sitesPressures,_getPackageDir,getObsSiteDataFrame,get_obssite_keys,is_obssite

# Check path

In [2]:
_getPackageDir()

'/Users/dagoret/anaconda3/envs/conda_py310/lib/python3.10/site-packages/getObsAtmo'

# Check Data

In [3]:
Dict_Of_sitesPressures

{'LSST': 731.50433,
 'CTIO': 774.6052,
 'OHP': 937.22595,
 'PDM': 710.90637,
 'OMK': 600.17224,
 'OSL': 1013.0}

# List of observatory

In [4]:
print(getObsSiteDataFrame())

     altitude   pressure
LSST    2.663  731.50433
CTIO    2.207   774.6052
OHP      0.65  937.22595
PDM    2.8905  710.90637
OMK     4.205  600.17224
OSL       0.0     1013.0


In [5]:
df = getObsSiteDataFrame()

In [6]:
df.index

Index(['LSST', 'CTIO', 'OHP', 'PDM', 'OMK', 'OSL'], dtype='object')

In [7]:
get_obssite_keys('lsst')

0     True
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [8]:
label = "LSST"

In [9]:
is_obssite('LSST')

True

In [25]:
is_obssite('AUXTEL')

True

# Check emul

In [10]:
emul =  ObsAtmo()

LSST is OK


In [11]:
emul =  ObsAtmo('CTIO')

CTIO is OK


In [12]:
 emul =  ObsAtmo('LSST',743.0)

LSST is OK


In [26]:
emul =  ObsAtmo('AuxTel',743.0)

LSST is OK


In [13]:
emul

In [14]:
wl = [400.,800.,900.]
am=1.2
pwv =4.0
oz=300.
transm = emul.GetAllTransparencies(wl,am,pwv,oz)

In [15]:
    >>> print("wavelengths (nm) \t = ",wl)
    >>> print("transmissions    \t = ",transm)    

wavelengths (nm) 	 =  [400.0, 800.0, 900.0]
transmissions    	 =  [0.72485491 0.97330618 0.85675228]


In [16]:
print(wl)

[400.0, 800.0, 900.0]


In [17]:
print(transm)

[0.72485491 0.97330618 0.85675228]


In [18]:
emul = ObsAtmo()
array = emul.GetAllTransparencies([300.,400.,600.,800.,1000.],1,0,0)

LSST is OK


In [19]:
array

array([0.41483073, 0.76797745, 0.95170851, 0.98476396, 0.9937721 ])

# Knowledge about grid

In [20]:
emul.WL[0:10]

array([300.        , 301.00125156, 302.00250313, 303.00375469,
       304.00500626, 305.00625782, 306.00750939, 307.00876095,
       308.01001252, 309.01126408])

In [21]:
emul.WL[-10:]

array([1090.98873592, 1091.98998748, 1092.99123905, 1093.99249061,
       1094.99374218, 1095.99499374, 1096.99624531, 1097.99749687,
       1098.99874844, 1100.        ])

In [22]:
emul.AIRMASS

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5])

In [23]:
emul.PWV

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,
        4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,
        6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,
        9.  ,  9.25,  9.5 ,  9.75, 10.  ])

In [24]:
emul.OZ

array([  0.,  25.,  50.,  75., 100., 125., 150., 175., 200., 225., 250.,
       275., 300., 325., 350., 375., 400., 425., 450., 475., 500., 525.,
       550., 575., 600.])