# Basic tests

- author : Sylvie Dagoret-Campagne
- affiliation : IJCLab/IN2P3/CNRS
- creation date : 2023/11/01
- update : 2024/08/27
- last update : 2025/06/15
- last update : 2025/10/15 : getObsAtmo version 0.2.0

In [1]:
import getObsAtmo
from getObsAtmo.getObsAtmo import ObsAtmo,Dict_Of_sitesPressures,_getPackageDir,get_obssite_dataframe,get_obssite_keys,is_obssite

### Check getObsAtmo version

In [2]:
print(f"{getObsAtmo.__name__} version {getObsAtmo._version.__version__}")

getObsAtmo version 0.2.1


### Check package path

In [3]:
_getPackageDir()

'/Users/dagoret/MacOSX/GitHub/LSST/2025/getObsAtmo/getObsAtmo'

### Check Data

In [4]:
Dict_Of_sitesPressures

{'LSST': 731.50433,
 'CTIO': 774.6052,
 'OHP': 937.22595,
 'ZTF': 823.60004,
 'VLT': 734.08038,
 'PDM': 710.90637,
 'OMK': 600.17224,
 'OSL': 1013.0}

### Pandas dataframe including the observatories in the package

In [5]:
print(get_obssite_dataframe())

     altitude   pressure
LSST    2.663  731.50433
CTIO    2.207   774.6052
OHP      0.65  937.22595
ZTF     1.712  823.60004
VLT     2.635  734.08038
PDM    2.8905  710.90637
OMK     4.205  600.17224
OSL       0.0     1013.0


In [6]:
df = get_obssite_dataframe()

In [7]:
df.index

Index(['LSST', 'CTIO', 'OHP', 'ZTF', 'VLT', 'PDM', 'OMK', 'OSL'], dtype='object')

In [8]:
get_obssite_keys('lsst')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

### Check labels

In [9]:
label = "LSST"

In [10]:
is_obssite('LSST')

True

In [11]:
is_obssite('AUXTEL')

True

### Check emul

In [12]:
emul =  ObsAtmo('LSST')

In [13]:
emul.Name

'Atmospheric emulator ObsAtmo for observation site LSST'

In [14]:
emul =  ObsAtmo('CTIO')

In [15]:
emul.Name

'Atmospheric emulator ObsAtmo for observation site CTIO'

In [16]:
emul =  ObsAtmo('LSST',743.0)

In [17]:
emul.Name

'Atmospheric emulator ObsAtmo for observation site LSST'

In [18]:
emul =  ObsAtmo('AuxTel',743.0)

In [19]:
emul.Name

'Atmospheric emulator ObsAtmo for observation site LSST'

### Check wavelengths

In [20]:
wl = [400.,800.,900.]
am=1.2
pwv =4.0
oz=300.
transm = emul.GetAllTransparencies(wl,am,pwv,oz)

In [21]:
    >>> print("wavelengths (nm) \t = ",wl)
    >>> print("transmissions    \t = ",transm)    

wavelengths (nm) 	 =  [400.0, 800.0, 900.0]
transmissions    	 =  [0.72485491 0.97330618 0.85675228]


In [22]:
print(wl)

[400.0, 800.0, 900.0]


In [23]:
print(transm)

[0.72485491 0.97330618 0.85675228]


In [24]:
emul = ObsAtmo()
array = emul.GetAllTransparencies([300.,400.,600.,800.,1000.],1,0,0)

In [25]:
array

array([0.41483073, 0.76797745, 0.95170851, 0.98476396, 0.9937721 ])

### Knowledge about the data grid

In [26]:
emul.WL[0:10]

array([300.        , 301.00125156, 302.00250313, 303.00375469,
       304.00500626, 305.00625782, 306.00750939, 307.00876095,
       308.01001252, 309.01126408])

In [27]:
emul.WL[-10:]

array([1090.98873592, 1091.98998748, 1092.99123905, 1093.99249061,
       1094.99374218, 1095.99499374, 1096.99624531, 1097.99749687,
       1098.99874844, 1100.        ])

In [28]:
emul.AIRMASS

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6])

In [29]:
emul.PWV

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,
        4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,
        6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,
        9.  ,  9.25,  9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  ,
       11.25, 11.5 , 11.75, 12.  , 12.25, 12.5 , 12.75, 13.  , 13.25,
       13.5 , 13.75, 14.  , 14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 ,
       15.75, 16.  , 16.25, 16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75,
       18.  , 18.25, 18.5 , 18.75, 19.  , 19.25, 19.5 , 19.75, 20.  ,
       20.25])

In [30]:
emul.OZ

array([  0.,  25.,  50.,  75., 100., 125., 150., 175., 200., 225., 250.,
       275., 300., 325., 350., 375., 400., 425., 450., 475., 500., 525.,
       550., 575., 600., 625.])